10250 bulk user data upload in keycloak
bcgov/moh-iam pull request #28
Opened 2023-07-06 22:46 UTC by daveb-hni

Program to handle updating Keycloak user info in a bulk upload. The program accepts a csv file with fields:
 	User - Roles
 	e.g. 
 	testuser1,"role_1, role_2"
 	testuser2,"role_1, role_3"
 
 Currently this program will:
- Add users if they don't exist
- Add the specified roles to the user. No roles are removed

 The program does not remove any user configuration and the same file can be imported multiple times to produce the same end result.

2023-07-11 18:18 UTC, weskubo-cgi requested changes

2023-07-12 23:50 UTC, daveb-hni commented on keycloak-data-loader/src/main/resources/configuration.properties
> +application=
Nearly always, client-id would be the ID of the client used to connect to keycloak, the 'admin-cli'. application is the app or client that the data is being loaded for.

2023-07-19 20:43 UTC, weskubo-cgi requested changes

2023-07-19 20:43 UTC, weskubo-cgi commented on keycloak-data-loader/README.md
> +		* username-type = This value will be used to indicate if a prefix or suffix is to be added to the supplied usernames. Valid values are specified in the UsernameTypeEnum, which defines the value to
I think the indented lists should only use a single tab in order to format correctly.

2023-07-19 20:43 UTC, weskubo-cgi commented on keycloak-data-loader/README.md
> +	* The required environment. Valid environment values are DEV, TEST, PROD.
I think the indented lists should only use a single tab in order to format correctly.

2023-07-19 20:43 UTC, weskubo-cgi commented on keycloak-data-loader/src/main/java/ca/bc/gov/hlth/iam/dataloader/Main.java
> +    	new Main().processDataLoad(args);
Technically this can be all static methods but that's just personal preference.

2023-07-19 21:35 UTC, weskubo-cgi approved these changes

2023-07-20 18:56 UTC, merged