Bulk generation of Keycloak clients for PPM API users
bcgov/moh-iam pull request #42
Opened 2024-07-18 16:07 UTC by daveb-hni

This application handles bulk generation of Keycloak Clients and their associated authentication certs. The clients are created with a default set of properties currently suited to creating clients for use by PPM API clients. The main characteristic of these clients is that they authenticate by "Signed JWT" so the application also produces these.

2024-08-22 00:56 UTC, arlowatts approved these changes

2024-08-29 22:27 UTC, arlowatts approved these changes

2024-08-30 16:46 UTC, arlowatts approved these changes

2025-04-07 22:03 UTC, gperkinscgi approved these changes
Reviewed and approved

2025-04-09 19:05 UTC, filipflorek requested changes

2025-04-09 19:13 UTC, filipflorek approved these changes

2025-04-09 22:23 UTC, merged